community/apps/bit-dev/app.tsx, workspace.jsonc
closed #34 
lock react-router-dom to be 5.2.0.
=> fix "cannot use link outside of router"

docs/entities/docs-routes/docs-route.ts, docs/entities/docs-routes/docs-routes.ts, docs/ui/community-docs/docs-routes.tsx, docs/ui/docs-tree-node/docs-node-title.tsx, docs/ui/docs-tree-node/docs-tree-node.composition.tsx, docs/ui/docs-tree-node/docs-tree-node.tsx, docs/ui/sidebar/sidebar.mock.tsx, docs/ui/sidebar/sidebar.tsx, pnpm-lock.yaml
=> change name of shurtcutPath to configPath for config section option

community/ui/heading/heading.module.scss, community/ui/pages/plugins/plugins.module.scss, community/ui/pages/plugins/plugins.tsx, community/ui/plugins/explore-section/explore-section.composition.tsx, community/ui/plugins/explore-section/explore-section.docs.mdx, community/ui/plugins/explore-section/explore-section.tsx
=> fix hightlight text in safari

docs/ui/docs-tree-node/docs-node-title.tsx, docs/ui/docs-tree-node/docs-tree-node.module.scss
=> fix sidebar config active state

docs/ui/community-docs/community-docs.composition.tsx, docs/ui/community-docs/community-docs.docs.mdx, docs/ui/community-docs/community-docs.tsx, docs/ui/community-docs/docs-routes.tsx, docs/ui/community-docs/getting-started-routes.tsx, docs/ui/community-docs/learn-routes.tsx, docs/ui/docs/docs.composition.tsx, docs/ui/docs/docs.docs.mdx, docs/ui/docs/docs.module.scss, docs/ui/docs/docs.tsx, docs/ui/docs/index.ts, docs/ui/pages/guides/guides.tsx, docs/ui/sidebar/sidebar.composition.tsx, docs/ui/sidebar/sidebar.mock.tsx, docs/ui/sidebar/sidebar.module.scss, docs/ui/sidebar/sidebar.tsx
=> separate docs sidebar tree to two categories, getting started and learn

.bitmap, community/apps/bit-dev/app.tsx, community/ui/hooks/use-local-storage/index.ts, community/ui/hooks/use-local-storage/use-local-storage.composition.tsx, community/ui/hooks/use-local-storage/use-local-storage.docs.mdx, community/ui/hooks/use-local-storage/use-local-storage.spec.tsx, community/ui/hooks/use-local-storage/use-local-storage.tsx
=> create locale storage hooks and use it in the highlighting

docs/ui/community-docs/community-docs.module.scss, docs/ui/community-docs/community-docs.tsx, docs/ui/docs/docs.tsx, docs/ui/sidebar/sidebar.tsx
=> add css option in categorie routes and fix empty tree node space

community/envs/community-react/community-react.main.runtime.ts, community/ui/logo-showcase/logo-showcase.module.scss
=> remove gray filter color from showcase logo

community/ui/pages/plugins/plugins.mock.tsx, workspace.jsonc
=> fix aspects link and description in plugins page

.bitmap
=> fix bitmap

community/ui/pages/plugins/plugins.mock.tsx
=> update netlify link in plugins page

.bitmap, docs/content/quick-start/demo-graph.ts, docs/content/thinking-in-components/thinking-in-components.mdx, docs/ui/sidebar/node-title/config-icon.tsx, docs/ui/sidebar/node-title/node-title.composition.tsx, docs/ui/sidebar/node-title/node-title.docs.mdx, pnpm-lock.yaml
=> fix location of undefined

.bitmap, pnpm-lock.yaml, workspace.jsonc
closed #122 
Fix only h3 for titles in docs, now they will be h1, h2, h3, h4, h5, h6.
=> Fix only h3 for titles in docs, now they will be h1, h2, h3, h4, h5, h6.

.bitmap, component/content/component-config/component-config.mdx, component/content/component-objects/component-objects.mdx, docs/ui/pages/doc-page/doc-page.tsx, pnpm-lock.yaml
=> change import positions to fix mdx content

community/entity/use-cases/use-cases.mocks.ts, community/ui/use-cases/use-cases-section/use-cases-section.spec.tsx, pnpm-lock.yaml
=> update use-cases-section, add links in the mock data and add tests

base-react/layout/panel/panel.tsx, bit/content/what-is-bit/what-is-bit.tsx, community/ui/community-highlighter/community-highlighter.composition.tsx, community/ui/community-highlighter/community-highlighter.spec.tsx, community/ui/community-highlighter/community-highlighter.tsx, community/ui/github-stars/github-stars.tsx, community/ui/mocks/bit-dev/bit-dev.tsx, design/blocks/header/header.composition.tsx, design/blocks/header/header.spec.tsx, design/blocks/header/header.tsx, docs/plugins/docs/table-of-contents/table-of-contents.composition.tsx, docs/plugins/docs/table-of-contents/table-of-contents.docs.mdx, docs/plugins/docs/table-of-contents/table-of-contents.spec.tsx, docs/plugins/docs/table-of-contents/table-of-contents.tsx, docs/plugins/next-page/next-page.spec.tsx, docs/ui/docs/docs.composition.tsx, docs/ui/pages/doc-page/doc-page.composition.tsx, docs/ui/pages/doc-page/doc-page.specx.tsx, docs/ui/pages/doc-page/doc-page.tsx
=> fix master errors

community/ui/community-highlighter/community-highlighter.module.scss, community/ui/header/header/header.module.scss
=> fix toggler align

docs/ui/docs/docs.docs.mdx
closed #152 
Update the live example to work like the composition.
=> Fix docs component live example

community/ui/footer/footer/footer.module.scss, design/blocks/footer/footer.module.scss, docs/plugins/docs/table-of-contents/table-of-contents.module.scss, docs/plugins/docs/table-of-contents/table-of-contents.tsx, docs/ui/hooks/use-element-on-fold/get-elements.tsx, docs/ui/hooks/use-element-on-fold/use-element-on-fold.composition.tsx, docs/ui/hooks/use-element-on-fold/use-element-on-fold.docs.mdx, docs/ui/hooks/use-element-on-fold/use-element-on-fold.spec.tsx, docs/ui/hooks/use-element-on-fold/use-element-on-fold.tsx, docs/ui/navigation/table-of-content/table-of-content.tsx
- use-elements-on-fold:
- added some tests and docs.
- added check for valid selectors
- plugin / table of content:
- added indentation
- removed collection of `h1`. so now only checks for `h2` & `h3`
- footer styles and cleanup
closed #158
=> Use element on fold improvements

community/content/getting-started/composing/create-components/create-components.mdx, component/content/adding-components/adding-components.mdx, component/content/component-objects/component-objects.mdx, component/content/inspecting-components/inspecting-components.mdx, component/content/navigate-history/navigate-history.mdx, component/content/snaps/snaps.mdx, component/content/tags/tags.mdx, dependencies/content/inspecting-dependencies/inspecting-dependencies.mdx, docs/content/getting-started/dev-envs/dev-envs.mdx, docs/content/getting-started/use-dependencies/use-dependencies.mdx, docs/ui/zoomable-image/image.tsx, workspace/content/importing-components/importing-components.mdx
=> moving img to image

.bitmap
=> tag and export

community/ui/graph/component-bubble/component-bubble.module.scss, community/ui/graph/component-bubble/component-bubble.tsx, design/ui/cards/bubble-card/bubble-card.module.scss, design/ui/cards/bubble-card/bubble-card.tsx
closed #211, closed #210 
- fixed bubbles having weird effect during intial load
- fixed client side routing (code was using the wrong context provider)
=> fix bubbles and routing

community/ui/pages/homepage/homepage.tsx
closed #210
make the data of the graph node static, should fix misplaced arrows
=> make graph-data static

community/entity/images/client-logos.mocks.ts
=> change enterprise logo in homepage

.bitmap, community/ui/bubble-highlighter/bubble-highlighter.tsx
=> bubble highlighter - forward classname to label

.bitmap, community/ui/graph/edge/edge.tsx
=> forward props to the edge component

.bitmap, community/ui/browser/browser-example/browser-snippet.demo.tsx, community/ui/browser/browser-example/browser.demo.tsx, community/ui/browser/browser-example/style.module.scss, community/ui/browser/browser.docs.mdx, community/ui/browser/browser.spec.tsx, community/ui/bubble-highlighter/bubble-highlighter.docs.mdx, community/ui/bubble-highlighter/example/highlight-button-with-label.mdx, community/ui/bubble-highlighter/example/highlight-button.demo.tsx, community/ui/bubble-highlighter/example/highlight-button.mdx, community/ui/cards/next-page/next-page.composition.tsx, community/ui/cards/next-page/next-page.spec.tsx, community/ui/cards/next-page/next-page.tsx, community/ui/community-highlighter/community-highlighter.docs.mdx, community/ui/community-highlighter/example/example-snippet.mdx, community/ui/community-highlighter/example/toggler-snippet.mdx, community/ui/community-highlighter/example/toggler.demo.tsx, community/ui/community-highlighter/example/use-highlighter-snippet.mdx, community/ui/community-highlighter/example/use-highlighter.demo.tsx, community/ui/github-stars/github-stars.docs.mdx, community/ui/github-stars/github-stars.spec.tsx, community/ui/github-stars/github-stars.tsx, community/ui/graph/edge/edge.tsx, community/ui/hooks/use-local-storage/use-local-storage.composition.tsx, community/ui/hooks/use-local-storage/use-local-storage.spec.tsx, community/ui/sections/top-down/top-down.composition.tsx, community/ui/sticky-menu/sticky-menu.docs.mdx, pnpm-lock.yaml
=> add tests, docs, checkout latest and tag-export

community/envs/community-mdx/community-mdx.preview.runtime.tsx, docs/ui/pages/doc-page/mdx-components.tsx
closed #234 
now looks like this:
=> highlighter for mdx components

base-react/navigation/link/index.ts, base-react/navigation/link/link.type.ts, base-react/navigation/link/navigation-provider.tsx, base-react/navigation/link/use-navigate.tsx, ui-foundation/ui/navigation/react-router-adapter/react-router-adapter.compositions.tsx, ui-foundation/ui/navigation/react-router-adapter/react-routing-provider.tsx
closed #236 
added new api - useNavigate()
=> new api - use navigate

envs/content/envs-overview/envs-overview.docs.mdx, envs/content/envs-overview/envs-overview.mdx, envs/content/extending-env/extending-env.docs.mdx, envs/content/extending-env/extending-env.mdx, envs/content/inspecting-env/inspecting-env.docs.mdx, envs/content/using-envs/using-envs.docs.mdx, envs/content/using-envs/using-envs.mdx
added all required docs for the new `bit env` command
=> add env command

docs/ui/community-docs/community-docs.composition.tsx, docs/ui/community-docs/community-docs.tsx, workspace.jsonc
closed #240 
fixed hidden mdx note titles
=> bump mdx-layout (new mdx colors)

docs/content/getting-started/ci-export/ci-export.mdx
=> adding install insturctions

community/content/getting-started/composing/create-components/create-components.mdx
=> fixed phrasing, removed variants

workspace/content/bitmap/bitmap.mdx, workspace/content/clearing-cache/clearing-cache.mdx, workspace/content/component-directory/component-directory.mdx, workspace/content/configuring-remote-scopes/configuring-remote-scopes.mdx, workspace/content/creating-components/creating-components.mdx, workspace/content/directory-structure/directory-structure.mdx, workspace/content/exporting-components/exporting-components.mdx, workspace/content/importing-components/importing-components.mdx, workspace/content/moving-components/moving-components.mdx, workspace/content/workspace-configuration/workspace-configuration.mdx, workspace/content/workspace-overview/workspace-overview.mdx, workspace/content/workspace-status/workspace-status.mdx
=> wrote docs for creating-components

scope/content/scope-overview/scope-overview.mdx
=> collaboration server

community/apps/bit-dev/app.tsx
=> fix gtm in bit-dev

community/ui/graph/bubble-graph/bubble-graph.tsx, community/ui/pages/homepage/homepage.tsx
=> Fix bubble arrows during first render

community/ui/graph/edge/auto-reloader.tsx, community/ui/graph/grid-graph/grid-graph.tsx, community/ui/sections/component-distribution/component-distribution.tsx
closed #316 
this will ensure the bubble graph are correctly positioned - by applying them inside a set interval
=> run bubble graph updater in a continuous interval

community/ui/plugins/explore-section/explore-section.tsx
=> Update browse aspects link in explore section

.github/workflows/pr.yaml
- github actions - print bit version 
- github actions - make sure we have various Ubuntu packages required for build
=> install ubuntu packages

community/ui/footer/footer/footer.module.scss
=> fix footer overflow to the right

community/apps/bit-dev/app-context.tsx, community/apps/bit-dev/app.tsx
closed #382
re-introduce application layout
=> fix layout (undo bad merge conflict)

workspace.jsonc
closed #372 
- highlighter will now NEVER overflow the document 🥇 
- this fixes some scroll issues in the docs page
=> improved highlighter

.bitmap, base-react/ui/layout/graph-node/graph-node.module.scss, bit/content/what-is-bit/what-is-bit.module.scss, bit/quick-start/learn-crossroad/learn-crossroad.module.scss, community/ui/community-highlighter/community-highlighter.module.scss, community/ui/features/features-card-grid/features-card-grid.module.scss, community/ui/footer/footer/footer.module.scss, community/ui/header/nav/nav.module.scss, community/ui/hero/hero.module.scss, community/ui/plugins/create-section/create-section.module.scss, community/ui/plugins/explore-section/explore-section.module.scss, community/ui/sections/component-distribution/component-distribution.module.scss, design/blocks/header/header.module.scss, design/ui/navigation/menu/menu.module.scss, docs/blocks/sidebar/sidebar.module.scss, docs/ui/docs/docs.module.scss, docs/ui/pages/doc-page/doc-page.module.scss
=> change all breakpoints to new api

harmony/content/cli-reference/cli-reference.mdx
=> fix cli reference titles

workspace.jsonc
=> update cloud provider

community/envs/community-mdx/community-mdx.main.runtime.ts, community/envs/community-react/community-react.main.runtime.ts
=> bump apollo client for envs to align it across other deps

base-react/ui/layout/graph-node/graph-node.module.scss, bit/content/what-is-bit/what-is-bit.module.scss, bit/quick-start/card/card.module.scss, community/ui/hero/hero.tsx, community/ui/pages/homepage/homepage.module.scss, community/ui/pages/homepage/homepage.tsx, community/ui/sections/component-distribution/component-distribution.module.scss, design/blocks/header/header.module.scss, design/blocks/header/header.tsx, workspace.jsonc
closed #413 
now with 100% less scroll
=> Fix horizontal scrolling in homepage

code/code/code.module.scss, code/code/code.tsx, community/component-showcase/component-showcase.module.scss, community/component-showcase/component-showcase.tsx, docs/ui/component-thinking-process/component-thinking-process.module.scss, workspace.jsonc
- **fixed showcase issues**
- fixed scroll issue
- fixed header styles (margins, paddings etc)
- **added responsive behavior**
- removed text from tabs in smaller res
- truncate component id when no room
- **code tab fixes:**
- fonts
- size
- layout - turns to top-down n smaller res
-  removed white background when code tab is loading
- fixed large fonts in drawer titles
closed #435
=> Showcase fix

community/envs/community-mdx/community-mdx.main.runtime.ts, community/envs/community-mdx/jest/jest.config.js
closed #429
This fixes jest errors on EMS for community-mdx
=> support esm in jest for community-mdx
